create extension if not exists pgcrypto;

create table if not exists public.quiz_sessions (
  id uuid primary key,
  quiz_name text not null,
  landing_url text,
  referrer text,
  user_agent text,
  utm jsonb default '{}'::jsonb,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  completed_at timestamptz,
  current_step_id text,
  current_step_slug text,
  current_step_title text,
  current_step_index integer,
  exit_step_id text,
  exit_step_slug text,
  exit_step_title text,
  answers_count integer not null default 0
);

create table if not exists public.quiz_events (
  id bigint generated by default as identity primary key,
  session_id uuid references public.quiz_sessions(id) on delete cascade,
  event_type text not null,
  step_id text,
  step_slug text,
  step_title text,
  step_type text,
  step_progress integer,
  step_index integer,
  value jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_answers (
  id bigint generated by default as identity primary key,
  session_id uuid references public.quiz_sessions(id) on delete cascade,
  step_id text not null,
  step_slug text,
  step_title text,
  step_type text,
  value jsonb default '{}'::jsonb,
  answered_at timestamptz not null default now(),
  unique (session_id, step_id)
);

create or replace function public.increment_answer_count(session_uuid uuid)
returns void
language sql
security definer
as $$
  update public.quiz_sessions
  set answers_count = (
    select count(*)::integer
    from public.quiz_answers
    where session_id = session_uuid
  ),
  last_seen_at = now()
  where id = session_uuid;
$$;

create or replace function public.reset_quiz_analytics()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.quiz_answers;
  delete from public.quiz_events;
  delete from public.quiz_sessions;
end;
$$;

alter table public.quiz_sessions enable row level security;
alter table public.quiz_events enable row level security;
alter table public.quiz_answers enable row level security;

drop policy if exists "public insert quiz sessions" on public.quiz_sessions;
drop policy if exists "public update quiz sessions" on public.quiz_sessions;
drop policy if exists "public read quiz sessions dashboard" on public.quiz_sessions;
drop policy if exists "public insert quiz events" on public.quiz_events;
drop policy if exists "public read quiz events dashboard" on public.quiz_events;
drop policy if exists "public insert quiz answers" on public.quiz_answers;
drop policy if exists "public read quiz answers dashboard" on public.quiz_answers;

create policy "public insert quiz sessions"
on public.quiz_sessions for insert
to anon
with check (true);

create policy "public update quiz sessions"
on public.quiz_sessions for update
to anon
using (true)
with check (true);

create policy "public read quiz sessions dashboard"
on public.quiz_sessions for select
to anon
using (true);

create policy "public insert quiz events"
on public.quiz_events for insert
to anon
with check (true);

create policy "public read quiz events dashboard"
on public.quiz_events for select
to anon
using (true);

create policy "public insert quiz answers"
on public.quiz_answers for insert
to anon
with check (true);

create policy "public update quiz answers"
on public.quiz_answers for update
to anon
using (true)
with check (true);

create policy "public read quiz answers dashboard"
on public.quiz_answers for select
to anon
using (true);

grant usage on schema public to anon;
grant select, insert, update on public.quiz_sessions to anon;
grant select, insert on public.quiz_events to anon;
grant select, insert, update on public.quiz_answers to anon;
grant execute on function public.increment_answer_count(uuid) to anon;
grant execute on function public.reset_quiz_analytics() to anon;
